---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: install os pkgs
  become: yes
  become_user: root
  with_items: '{{corkscrew_os_pkgs}}'
  package:
    name: '{{item}}'
    state: present

- name: check for corkscrew binary
  when: corkscrew_build
  stat:
    path: /usr/local/bin/corkscrew
  register: corkscrew_present

- name: perform build
  when: corkscrew_build and corkscrew_present.stat.exists == False
  become: yes
  become_user: root
  include: build.yml
