---
- name: download tgz
  get_url: >
    url={{corkscrew_url}}
    dest=/tmp/{{corkscrew_tgz}}
    mode=644

- name: unarchive
  unarchive: >
    copy=no
    src=/tmp/{{corkscrew_tgz}}
    dest=/opt
    creates=/opt/corkscrew-{{corkscrew_version}}

- name: configure it
  command: ./configure
  args:
    chdir: '/opt/corkscrew-{{corkscrew_version}}'
    creates: '/opt/corkscrew-{{corkscrew_version}}/Makefile'

- name: build it
  command: make install
  args:
    chdir: '/opt/corkscrew-{{corkscrew_version}}'
    creates: /usr/local/bin/corkscrew
